#!/usr/bin/env node
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const FRONTEND_ROOT = join(__dirname, '..');
const CONTRACT_ROOT = join(FRONTEND_ROOT, '..', 'fhevm-hardhat-template');
const ABI_OUTPUT_DIR = join(FRONTEND_ROOT, 'abi');

// Ensure output directory exists
if (!existsSync(ABI_OUTPUT_DIR)) {
  mkdirSync(ABI_OUTPUT_DIR, { recursive: true });
}

// Contract name
const CONTRACT_NAME = 'TalkletReview';

// Network configurations: [networkName, chainId]
const NETWORKS = [
  ['localhost', 31337],
  ['sepolia', 11155111],
];

try {
  // Collect deployments from all networks
  const addresses = {};
  let deployment = null;

  for (const [networkName, chainId] of NETWORKS) {
    const deploymentsDir = join(CONTRACT_ROOT, 'deployments', networkName);
    const deploymentPath = join(deploymentsDir, `${CONTRACT_NAME}.json`);
    
    if (existsSync(deploymentPath)) {
      const networkDeployment = JSON.parse(readFileSync(deploymentPath, 'utf-8'));
      addresses[chainId] = networkDeployment.address;
      
      // Use the first available deployment for ABI (they should be the same)
      if (!deployment) {
        deployment = networkDeployment;
      }
      
      console.log(`✓ Found deployment on ${networkName} (chainId: ${chainId}): ${networkDeployment.address}`);
    } else {
      console.warn(`⚠️  Deployment not found for ${networkName} (chainId: ${chainId})`);
    }
  }

  if (!deployment) {
    console.warn(`⚠️  No deployment files found for ${CONTRACT_NAME}`);
    console.warn('   Run "npx hardhat deploy --network localhost" or "--network sepolia" first');
    
    // Fallback: Check if address mapping file exists, if so, keep it and try to read ABI from existing file
    const existingAddressFile = join(ABI_OUTPUT_DIR, `${CONTRACT_NAME}Addresses.ts`);
    const existingABIFile = join(ABI_OUTPUT_DIR, `${CONTRACT_NAME}ABI.ts`);
    
    if (existsSync(existingAddressFile) && existsSync(existingABIFile)) {
      console.log('✓ Using existing ABI and address mapping files');
      process.exit(0); // Exit gracefully, use existing files
    }
    
    // Last resort: Use hardcoded Sepolia address (for Vercel builds)
    console.log('⚠️  Using fallback Sepolia address for build');
    addresses[11155111] = '0xCe389EEEbfB807D0CF43a7F3C0a9BC127Abc5521';
    
    // Try to read ABI from artifacts (if available)
    const artifactsDir = join(CONTRACT_ROOT, 'artifacts', 'contracts', `${CONTRACT_NAME}.sol`);
    const artifactPath = join(artifactsDir, `${CONTRACT_NAME}.json`);
    
    if (existsSync(artifactPath)) {
      const artifact = JSON.parse(readFileSync(artifactPath, 'utf-8'));
      deployment = { abi: artifact.abi };
      console.log('✓ Found ABI in artifacts');
    } else {
      console.error('❌ Cannot generate ABI: No deployment files or artifacts found');
      process.exit(1);
    }
  }

  // Generate ABI file
  const abiContent = `// Auto-generated by genabi.mjs
export const ${CONTRACT_NAME}ABI = ${JSON.stringify(deployment.abi, null, 2)} as const;
`;

  writeFileSync(join(ABI_OUTPUT_DIR, `${CONTRACT_NAME}ABI.ts`), abiContent);

  // Generate address mapping file
  const addressEntries = Object.entries(addresses)
    .map(([chainId, address]) => `  ${chainId}: "${address}", // ${NETWORKS.find(([_, id]) => id.toString() === chainId)?.[0] || 'Unknown'}`)
    .join('\n');

  const addressContent = `// Auto-generated by genabi.mjs
export const ${CONTRACT_NAME}Addresses: Record<number, string> = {
${addressEntries}
};

export function get${CONTRACT_NAME}Address(chainId: number): string | undefined {
  return ${CONTRACT_NAME}Addresses[chainId];
}
`;

  writeFileSync(join(ABI_OUTPUT_DIR, `${CONTRACT_NAME}Addresses.ts`), addressContent);

  console.log('✅ ABI and address mapping generated successfully');
  console.log(`   - ${join(ABI_OUTPUT_DIR, `${CONTRACT_NAME}ABI.ts`)}`);
  console.log(`   - ${join(ABI_OUTPUT_DIR, `${CONTRACT_NAME}Addresses.ts`)}`);
} catch (error) {
  console.error('❌ Error generating ABI:', error.message);
  process.exit(1);
}

